## Import Tables

### Customers Table

In [11]:
import pandas as pd

df_Customers = pd.read_csv('customers.csv')
df_Customers

   customer_id first_name last_name        city  age            email
0            1      Ahmed    Hassan       Cairo   25  ahmed@email.com
1            2       Sara       Ali        Giza   31   sara@email.com
2            3       Omar   Mohamed       cairo   17   omar@email.com
3            4       Mona   Ibrahim  Alexandria   28              NaN
4            5      Ahmed    Hassan       Cairo   25  ahmed@email.com

### Orders Table

In [12]:
df_Orders = pd.read_parquet("orders.parquet")
df_Orders

    order_id  customer_id  product_id  quantity order_date
0       1001            1         101         2 2026-09-01
1       1002            2         102         1 2026-09-01
2       1003            3         103         3 2026-09-02
3       1004            4         101         1 2026-09-02
4       1005            1         104         2 2026-09-03
5       1006            5         102         1 2026-09-03
6       1007            2         105         4 2026-09-04
7       1008            3         101         1 2026-09-04
8       1009            4         103         2 2026-09-05
9       1010            1         104         1 2026-09-05
10      1003            3         103         3 2026-09-02

### Products Table

In [13]:
url = "https://raw.githubusercontent.com/MohammedHameds/test1455/refs/heads/main/products.csv"
df_Products = pd.read_csv(url)

df_Products

   product_id product_name     category  unit_price
0         101       Laptop  Electronics       25000
1         102        Mouse  Accessories         500
2         103     Keyboard  Accessories        1200
3         104      Monitor  Electronics        7000
4         105   Headphones  Accessories        2500
5         106       Webcam  Accessories        1800

In [14]:
#Tables Names:
#df_Customers
#df_Orders
#df_Products

## 🔄 Data Cleaning

### Customers Table

In [15]:
df_Customers

   customer_id first_name last_name        city  age            email
0            1      Ahmed    Hassan       Cairo   25  ahmed@email.com
1            2       Sara       Ali        Giza   31   sara@email.com
2            3       Omar   Mohamed       cairo   17   omar@email.com
3            4       Mona   Ibrahim  Alexandria   28              NaN
4            5      Ahmed    Hassan       Cairo   25  ahmed@email.com

In [16]:
df_Customers.duplicated().sum()

np.int64(0)

In [17]:
df_Customers.isnull().sum()

customer_id    0
first_name     0
last_name      0
city           0
age            0
email          1
dtype: int64

In [18]:
df_Customers.replace("cairo","Cairo", inplace=True)

   customer_id first_name last_name        city  age            email
0            1      Ahmed    Hassan       Cairo   25  ahmed@email.com
1            2       Sara       Ali        Giza   31   sara@email.com
2            3       Omar   Mohamed       Cairo   17   omar@email.com
3            4       Mona   Ibrahim  Alexandria   28              NaN
4            5      Ahmed    Hassan       Cairo   25  ahmed@email.com

In [19]:
df_Customers["email"] = df_Customers["email"].fillna("no email", inplace=True)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_28960\3784770104.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_Customers["email"] = df_Customers["email"].fillna("no email", inplace=True)

In [20]:
df_Customers["email"] = df_Customers["email"].replace("no email", "Ibrahim@email.com", inplace=True)
df_Customers

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_28960\1622079147.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_Customers["email"] = df_Customers["email"].replace("no email", "Ibrahim@email.com", inplace=True)

   customer_id first_name last_name        city  age              email
0            1      Ahmed    Hassan       Cairo   25    ahmed@email.com
1            2       Sara       Ali        Giza   31     sara@email.com
2            3       Omar   Mohamed       Cairo   17     omar@email.com
3            4       Mona   Ibrahim  Alexandria   28  Ibrahim@email.com
4            5      Ahmed    Hassan       Cairo   25    ahmed@email.com

In [21]:
df_Customers["Full Name"] = df_Customers["first_name"] + " " + df_Customers["last_name"]
df_Customers

,customer_id,first_name,last_name,city,age,email,Full Name
0,1,Ahmed,Hassan,Cairo,25,ahmed@email.com,Ahmed Hassan
1,2,Sara,Ali,Giza,31,sara@email.com,Sara Ali
2,3,Omar,Mohamed,Cairo,17,omar@email.com,Omar Mohamed
3,4,Mona,Ibrahim,Alexandria,28,Ibrahim@email.com,Mona Ibrahim
4,5,Ahmed,Hassan,Cairo,25,ahmed@email.com,Ahmed Hassan

### Orders Table

In [22]:
df_Orders

    order_id  customer_id  product_id  quantity order_date
0       1001            1         101         2 2026-09-01
1       1002            2         102         1 2026-09-01
2       1003            3         103         3 2026-09-02
3       1004            4         101         1 2026-09-02
4       1005            1         104         2 2026-09-03
5       1006            5         102         1 2026-09-03
6       1007            2         105         4 2026-09-04
7       1008            3         101         1 2026-09-04
8       1009            4         103         2 2026-09-05
9       1010            1         104         1 2026-09-05
10      1003            3         103         3 2026-09-02

In [23]:
df_Orders.drop_duplicates(subset=["order_id"], inplace=True)
df_Orders

   order_id  customer_id  product_id  quantity order_date
0      1001            1         101         2 2026-09-01
1      1002            2         102         1 2026-09-01
2      1003            3         103         3 2026-09-02
3      1004            4         101         1 2026-09-02
4      1005            1         104         2 2026-09-03
5      1006            5         102         1 2026-09-03
6      1007            2         105         4 2026-09-04
7      1008            3         101         1 2026-09-04
8      1009            4         103         2 2026-09-05
9      1010            1         104         1 2026-09-05

In [24]:

invalid_quantities = df_Orders[df_Orders["quantity"] <= 0]
invalid_quantities

df_Orders["quantity"].isnull().sum()

np.int64(0)

In [25]:
invalid_quantities

Empty DataFrame
Columns: [order_id, customer_id, product_id, quantity, order_date]
Index: []

In [26]:
df_Orders.dtypes
df_Orders["order_date"] = pd.to_datetime(df_Orders["order_date"])

In [27]:
df_Orders.dtypes

order_id                int64
customer_id             int64
product_id              int64
quantity                int64
order_date     datetime64[us]
dtype: object

In [28]:
df_Orders

   order_id  customer_id  product_id  quantity order_date
0      1001            1         101         2 2026-09-01
1      1002            2         102         1 2026-09-01
2      1003            3         103         3 2026-09-02
3      1004            4         101         1 2026-09-02
4      1005            1         104         2 2026-09-03
5      1006            5         102         1 2026-09-03
6      1007            2         105         4 2026-09-04
7      1008            3         101         1 2026-09-04
8      1009            4         103         2 2026-09-05
9      1010            1         104         1 2026-09-05

In [29]:
invalid_Customer_ids = df_Orders[df_Orders["customer_id"].isin(df_Customers["customer_id"]) == False]
invalid_Customer_ids

Empty DataFrame
Columns: [order_id, customer_id, product_id, quantity, order_date]
Index: []

In [30]:
invalid_product_ids = df_Orders[df_Orders["product_id"].isin(df_Products["product_id"]) == False]
invalid_product_ids

Empty DataFrame
Columns: [order_id, customer_id, product_id, quantity, order_date]
Index: []

### Products Table

In [31]:
df_Products.duplicated().sum()

np.int64(0)

In [32]:
df_Products

   product_id product_name     category  unit_price
0         101       Laptop  Electronics       25000
1         102        Mouse  Accessories         500
2         103     Keyboard  Accessories        1200
3         104      Monitor  Electronics        7000
4         105   Headphones  Accessories        2500
5         106       Webcam  Accessories        1800

In [33]:
df_Products.drop_duplicates()

   product_id product_name     category  unit_price
0         101       Laptop  Electronics       25000
1         102        Mouse  Accessories         500
2         103     Keyboard  Accessories        1200
3         104      Monitor  Electronics        7000
4         105   Headphones  Accessories        2500
5         106       Webcam  Accessories        1800

In [34]:
df_Products["category"].value_counts()

category
Accessories    4
Electronics    2
Name: count, dtype: int64

In [35]:
## Unit Price is Valid

In [36]:
df_Products['unit_price'] = pd.to_numeric(df_Products['unit_price'], errors='coerce')

In [37]:
df_Products.dtypes

product_id      int64
product_name      str
category          str
unit_price      int64
dtype: object

In [38]:
df_Products

   product_id product_name     category  unit_price
0         101       Laptop  Electronics       25000
1         102        Mouse  Accessories         500
2         103     Keyboard  Accessories        1200
3         104      Monitor  Electronics        7000
4         105   Headphones  Accessories        2500
5         106       Webcam  Accessories        1800

## Marged Data

In [39]:

merged_df = pd.merge(df_Orders, df_Customers, on='customer_id', how='left')

final_df = pd.merge(merged_df, df_Products, on='product_id', how='left')

final_df

,order_id,customer_id,product_id,quantity,order_date,first_name,last_name,city,age,email,Full Name,product_name,category,unit_price
0,1001,1,101,2,2026-09-01,Ahmed,Hassan,Cairo,25,ahmed@email.com,Ahmed Hassan,Laptop,Electronics,25000
1,1002,2,102,1,2026-09-01,Sara,Ali,Giza,31,sara@email.com,Sara Ali,Mouse,Accessories,500
2,1003,3,103,3,2026-09-02,Omar,Mohamed,Cairo,17,omar@email.com,Omar Mohamed,Keyboard,Accessories,1200
3,1004,4,101,1,2026-09-02,Mona,Ibrahim,Alexandria,28,Ibrahim@email.com,Mona Ibrahim,Laptop,Electronics,25000
4,1005,1,104,2,2026-09-03,Ahmed,Hassan,Cairo,25,ahmed@email.com,Ahmed Hassan,Monitor,Electronics,7000
5,1006,5,102,1,2026-09-03,Ahmed,Hassan,Cairo,25,ahmed@email.com,Ahmed Hassan,Mouse,Accessories,500
6,1007,2,105,4,2026-09-04,Sara,Ali,Giza,31,sara@email.com,Sara Ali,Headphones,Accessories,2500
7,1008,3,101,1,2026-09-04,Omar,Mohamed,Cairo,17,omar@email.com,Omar Mohamed,Laptop,Electronics,25000
8,1009,4,103,2,2026-09-05,Mona,Ibrahim,Alexandria,28,Ibrahim@email.com,Mona Ibrahim,Keyboard,Accessories,1200
9,1010,1,104,1,2026-09-05,Ahmed,Hassan,Cairo,25,ahmed@email.com,Ahmed Hassan,Monitor,Electronics,7000

## 💰 Total Salary

In [40]:
final_df["total_amount"] = final_df["quantity"] * final_df["unit_price"]

In [41]:
final_df

,order_id,customer_id,product_id,quantity,order_date,first_name,last_name,city,age,email,Full Name,product_name,category,unit_price,total_amount
0,1001,1,101,2,2026-09-01,Ahmed,Hassan,Cairo,25,ahmed@email.com,Ahmed Hassan,Laptop,Electronics,25000,50000
1,1002,2,102,1,2026-09-01,Sara,Ali,Giza,31,sara@email.com,Sara Ali,Mouse,Accessories,500,500
2,1003,3,103,3,2026-09-02,Omar,Mohamed,Cairo,17,omar@email.com,Omar Mohamed,Keyboard,Accessories,1200,3600
3,1004,4,101,1,2026-09-02,Mona,Ibrahim,Alexandria,28,Ibrahim@email.com,Mona Ibrahim,Laptop,Electronics,25000,25000
4,1005,1,104,2,2026-09-03,Ahmed,Hassan,Cairo,25,ahmed@email.com,Ahmed Hassan,Monitor,Electronics,7000,14000
5,1006,5,102,1,2026-09-03,Ahmed,Hassan,Cairo,25,ahmed@email.com,Ahmed Hassan,Mouse,Accessories,500,500
6,1007,2,105,4,2026-09-04,Sara,Ali,Giza,31,sara@email.com,Sara Ali,Headphones,Accessories,2500,10000
7,1008,3,101,1,2026-09-04,Omar,Mohamed,Cairo,17,omar@email.com,Omar Mohamed,Laptop,Electronics,25000,25000
8,1009,4,103,2,2026-09-05,Mona,Ibrahim,Alexandria,28,Ibrahim@email.com,Mona Ibrahim,Keyboard,Accessories,1200,2400
9,1010,1,104,1,2026-09-05,Ahmed,Hassan,Cairo,25,ahmed@email.com,Ahmed Hassan,Monitor,Electronics,7000,7000

## Final Table

In [42]:
final_df = final_df[["order_id","Full Name","product_name", "quantity", "unit_price", "total_amount"]]

In [43]:
final_df

   order_id     Full Name product_name  quantity  unit_price  total_amount
0      1001  Ahmed Hassan       Laptop         2       25000         50000
1      1002      Sara Ali        Mouse         1         500           500
2      1003  Omar Mohamed     Keyboard         3        1200          3600
3      1004  Mona Ibrahim       Laptop         1       25000         25000
4      1005  Ahmed Hassan      Monitor         2        7000         14000
5      1006  Ahmed Hassan        Mouse         1         500           500
6      1007      Sara Ali   Headphones         4        2500         10000
7      1008  Omar Mohamed       Laptop         1       25000         25000
8      1009  Mona Ibrahim     Keyboard         2        1200          2400
9      1010  Ahmed Hassan      Monitor         1        7000          7000

## 🗄️ Connect to  SQL Server

In [44]:
import pyodbc
conn = pyodbc.connect(                     
    "driver={ODBC Driver 17 for SQL Server};"
    "server=localhost;"
    "database=all_data;"
    "trusted_connection=yes;"
) 

code = """ create table final_df ( order_id int, Full_Name varchar(50), product_name varchar(50), quantity int, unit_price int, total_amount int )  """
cursor = conn.cursor()

cursor.execute(code) 
conn.commit()

cursor.close()
conn.close()

ProgrammingError: ('42S01', "[42S01] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]There is already an object named 'final_df' in the database. (2714) (SQLExecDirectW)")

In [ ]:
conn = pyodbc.connect(                     
    "driver={ODBC Driver 17 for SQL Server};"
    "server=localhost;"
    "database=all_data;"
    "trusted_connection=yes;"
) 

cursor = conn.cursor()
cursor.executemany('insert into final_df (order_id, Full_Name, product_name, quantity, unit_price, total_amount) values (?, ?, ?, ?, ?, ?)',final_df.values.tolist())

conn.commit()

cursor.close()
conn.close()

In [ ]:
conn = pyodbc.connect(                     
    "driver={ODBC Driver 17 for SQL Server};"
    "server=localhost;"
    "database=all_data;"
    "trusted_connection=yes;"
) 
cursor = conn.cursor()
cursor.execute('select * from final_df')

conn.commit()

cursor.close()
conn.close()

## 🌐 Flask Dashboard

In [45]:
from flask import Flask, render_template
import pandas as pd
import pyodbc

app = Flask(__name__)


conn_str = (
    "DRIVER={ODBC Driver 17 for SQL Server};"
    "SERVER=localhost;"
    "DATABASE=all_data;"
    "Trusted_Connection=yes;"
)


@app.route("/")
def dashboard():
  try:
    conn = pyodbc.connect(conn_str)
    query = "SELECT * FROM final_df"
    df = pd.read_sql(query, conn)
    conn.close()

    columns = df.columns.values
    rows = df.values.tolist()

    return render_template(
        "index.html", columns=columns, rows=rows, error=None
    )

  except Exception as e:
    return render_template("index.html", columns=[], rows=[], error=str(e))


if __name__ == '__main__':
    app.run(debug=False, use_reloader=False)

 * Serving Flask app '__main__'
 * Debug mode: off

WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_28960\571224953.py:21: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
127.0.0.1 - - [27/Sep/2026 00:57:57] "GET / HTTP/1.1" 200 -